/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.ucsd.cse110;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testMakeAnAppInstance() {
        App a = new App();
        assertNotNull(a);
    }

    @Test
    public void thisShouldPass1() {
        assertEquals(4, 2+2);
    }

    @Test
    public void thisShouldPass() {
        assertFalse(false);
    }
}
